version: '3.8'
services:
  db:
    image: postgres:15
    container_name: if4040-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: project0_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
    restart: unless-stopped